### PR TITLE
Harbir Reuploading Completed Snippets Challenge

### PR DESCRIPTION
**Pull request by Harbir01**

### CODE REVIEW

**Comment by keyuyan1145** [comment]
What's the reason for re-upload?

**Comment by Harbir01** [comment]
the reason for the upload was because I didn't see it in my folder locally, because I had pushed it but for some reason i didn't see it on GitHub either...  Apologies Boss
________________________________

**Comment by keyuyan1145** [comment]
Check your folder again. I think I see the snippet challenge in your folder.

**Comment by Harbir01** [comment]
Yes I believe when I reuploaded it, I made two copies.

The reason I reuploaded it was because  when I originally pushed the item it disappeared form my vs code and I wasn’t sure if it went threw cause I didn’t see it on vs code or GitHub.

Sorry about that we can ignore it or I can go back and remove and clean, organize my account.

**Comment by keyuyan1145** [comment]
I see both the snippet and stock market challenges in your folder, so I will close this PR.

**Pull request closed without merging**
