### PR TITLE
Blaine SNIPPETS Challenge Week 2

### PR DESCRIPTION
**Pull request by Blaine-Reid**
This is the completed Snippets Challenge

### CODE REVIEW

**Review by keyuyan1145 — COMMENTED** [review]
Code snippet #5 has assertionError.

**Comment by Blaine-Reid** [comment]
I ran mine on my computer and don't have an assertion error

**Comment by Blaine-Reid** [comment]
I see why, mine has m != n on line 69 were the pushed has m==n

**Comment by Blaine-Reid** [comment]
Not sure why even my branch has correct code and the push doesnt

**Pull request closed without merging**
