### PR TITLE
Blaine wk4 functions

### PR DESCRIPTION
**Pull request by Blaine-Reid**
wk4 functions challenge completed

### CODE REVIEW

**Review by keyuyan1145 — COMMENTED** [review]
Take another look at Question 2.3. Your current implementation captures a superset of what the question asks for. Consider what happens there's another book in the list written by 'Timothy Snyder Zeller' and I search by 'Timothy Snyder'.

**Comment by Blaine-Reid** [comment]
I updated the function to require that the string length given as the author argument matches the length of the string in the object

**Review by keyuyan1145 — COMMENTED** [review]
Yes, that should do it, but there's a more straightforward way to do that. One condition will suffice.

**Review by keyuyan1145 — APPROVED** [review]
Looks good!

**Pull request merged**
