### PR TITLE
Manuela restaurants challenge

### PR DESCRIPTION
**Pull request by 1mfarhi**
hello, I have added the restaurants challenge
thanks

### CODE REVIEW

**Review by 1mfarhi — COMMENTED** [review]
I do not know what comment I need . Please help me

**Review by 1mfarhi — COMMENTED** [review]
I do not understand what  to do , please help

**Comment by 1mfarhi** [comment]
please let me know what to do

**Review by keyuyan1145 — APPROVED** [review]
Looks good!

**Pull request merged**
