### PR TITLE
allison completed spotify challenge

### PR DESCRIPTION
**Pull request by 42-allison-k**

### CODE REVIEW

**Review by keyuyan1145 — COMMENTED** [review]
For Question 1a, do you need to make any changes to the "Song" table?

**Comment by 42-allison-k** [comment]
The Genre column in the songs table would contain the id of the genre instead of the name.

**Comment by keyuyan1145** [comment]
Awesome!

**Review by keyuyan1145 — APPROVED** [review]
Looks good

**Pull request merged**
