### PR TITLE
allison completed loops challenge

### PR DESCRIPTION
**Pull request by 42-allison-k**
adding my completed loops challenge

### CODE REVIEW

**Review by keyuyan1145 — COMMENTED** [review]
Everything else looks good, but take a look at Q4. If you give temp < 65, it will print indefinitely.

**Comment by 42-allison-k** [comment]
@keyuyan1145 would adding break at the end fix that. I am a bit confused because I did not get stuck in a loop when I ran it and tried lots of number to be sure.

**Comment by 42-allison-k** [comment]
Never mind, I got it. I will push it as soon as I get home from work.

**Review by keyuyan1145 — APPROVED** [review]
Looks good!

**Pull request merged**
