### PR TITLE
allison completed bikes challenge

### PR DESCRIPTION
**Pull request by 42-allison-k**

### CODE REVIEW

**Review by keyuyan1145 — APPROVED** [review]
Looks good!

**Comment by keyuyan1145** [comment]
**Note: submit grade once assignment added to Canvas.**

**Comment by keyuyan1145** [comment]
Since both challenges are listed under one assignment on Canvas, could you push your `checking_challenge.py` here as well? I will submit a grade for both altogether.

**Comment by 42-allison-k** [comment]
Checking Challenge is not added to this branch

**Review by keyuyan1145 — APPROVED** [review]
Looks great!

**Pull request merged**
